### ISSUE TITLE
Placeholder Prefix

### ISSUE THREAD

**Issue by raffy99** [b03tz/MinifyX#1]
Placeholder Prefix seems to be MinifyX not Minified as documented

**Comment by b03tz** [comment]
Where is this documented? It is correct on the rtfm: http://rtfm.modx.com/display/ADDON/MinifyX

**Comment by raffy99** [comment]
i just took a look in the source code, because the documented placeholder didn't work.
[[+MinifyX.css]] works for me
[[+Minified.css]] didn't work for me

minifyx.class.php Line 154
....

$modx->toPlaceholders(array(
    'javascript' => '<script type="text/javascript" src="'.str_replace('//', '/', $cacheFolderUrl.'/'.$cacheHashJs).'.js"></script>',
    'css' => '<link rel="stylesheet" type="text/css" href="'.str_replace('//', '/', $cacheFolderUrl.'/'.$cacheHashCss).'.css" />',
), 'MinifyX');

....

**Comment by b03tz** [comment]
I know, but where do you get the [[+Minified]] from? You must have read that somewhere, where :-)

**Comment by b03tz** [comment]
Ah, in the example code ;) I see now...it is fixed

**Comment by raffy99** [comment]
Ah, didn't look at the Placeholder Section :-) Just had a quick look at 
the examples, copy & paste ....

Am 28.03.2012 12:16, schrieb Patrick Nijkamp:

**Comment by b03tz** [comment]
It's okay! It's resolved now, thanks for the report!
