### ISSUE TITLE
How to change cache file when source file changes?

### ISSUE THREAD

**Issue by vierkantemeter** [b03tz/MinifyX#10]
When I edit the source css file, the cached file doesn't change. I have to change the title of the css file to generate a new cache file. Is this the only way to do this or am I missing something?

**Comment by b03tz** [comment]
Just empty your cache after a modification. And disable cache whilst editing
Op 17 jan. 2014 13:46 schreef "vierkantemeter" notifications@github.com:

**Comment by vierkantemeter** [comment]
oh, now I feel stupid ;-) Yesterday that didn't seem to work but tested again and now it does. Thank you!
