### ISSUE TITLE
Plugin does not parse relative URLs in CSS

### ISSUE THREAD

**Issue by Triplethread** [b03tz/MinifyX#2]
Hello,

first problem of today (there is another) of this handy plugin is that it dont parse relative URLs in CSS.

not working:

``` css
@font-face 
    {
    font-family:'TraditionellSans-Bold';
    src:url('../fonts/TraditionellSans-Bold.eot');
```

is working:

``` css
@font-face 
    {
    font-family:'TraditionellSans-Bold';
    src:url('my_path_of_installation_/assets/foundation/fonts/TraditionellSans-Bold.eot');
```

**Comment by b03tz** [comment]
If you read the manual:

http://rtfm.modx.com/display/ADDON/MinifyX#MinifyX-Whatyouneedtoknow

It clearly states that MinifyX only supports absolute URLs. Relative URLs will not be supported in the future.

**Comment by Triplethread** [comment]
Oh I am very sorry, 2 hours of try and error can save 10 minutes of manual reading!
Would change that issue to a feature request…
